[application]

# App (Project) Name
name = "hell-dioxus"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]
# base_path = "https://github.com/RNubla/hello-dioxus.git"

# HTML title tag content
title = "hello-dioxus"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]
# script = ["https://cdn.jsdelivr.net/npm/theme-change@2.0.2/index.js"]

# CSS style file

style = ["tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
